// Generated by flutterfire_cli from google-services.json and GoogleService-Info.plist.
// Do not edit — regenerate with `flutterfire configure` if Firebase project changes.
library;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web is not supported.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApwFGs_VDZXgPi6BmfuIuRML4sc10pK2Y',
    appId: '1:787717492493:android:8c3170a5bb61f54a676a44',
    messagingSenderId: '787717492493',
    projectId: 'noor-companion-2026',
    storageBucket: 'noor-companion-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7uA1GgBQit9bz9K6AfNhcVPVPGKrp7xs',
    appId: '1:787717492493:ios:0bb1cf3f77a45efb676a44',
    messagingSenderId: '787717492493',
    projectId: 'noor-companion-2026',
    storageBucket: 'noor-companion-2026.firebasestorage.app',
    iosBundleId: 'com.noorcompanion.app',
  );
}
