/// Noor Companion — app entry point.
/// Init order: Sentry → WidgetsBinding → Supabase → Hive → Firebase → runApp.
/// Sentry is first so it captures any startup errors.
library;

// firebase_core and firebase_options are activated once `flutterfire configure`
// is run with real project credentials. Uncomment the lines below at that point.
// import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:sentry_flutter/sentry_flutter.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'core/config/app_config.dart';
import 'features/content/data/content_cache.dart';
import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
// import 'firebase_options.dart'; // generated by `flutterfire configure`

Future<void> main() async {
  await SentryFlutter.init(
    (options) {
      options.dsn = AppConfig.sentryDsn;
      options.environment = AppConfig.environment;
      options.tracesSampleRate = AppConfig.isDevelopment ? 1.0 : 0.2;
    },
    appRunner: _initAndRun,
  );
}

Future<void> _initAndRun() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Supabase.initialize(
    url: AppConfig.supabaseUrl,
    anonKey: AppConfig.supabaseAnonKey,
  );

  await Hive.initFlutter();
  await openContentBoxes();

  // Firebase.initializeApp — uncomment after running `flutterfire configure`
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const ProviderScope(child: NoorApp()));
}

/// Root application widget.
/// ConsumerWidget so it can pass the Riverpod ref to the router.
class NoorApp extends ConsumerWidget {
  const NoorApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = buildAppRouter(ref);

    return MaterialApp.router(
      title: 'Noor Companion',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      routerConfig: router,
    );
  }
}
